### ISSUE TITLE
Error when puck enters a goal

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#67]
```
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    gameLoop(7)
  File "main.py", line 125, in gameLoop
    puck.reset()
TypeError: reset() takes exactly 2 arguments (1 given)

```

**Comment by Aniq55** [comment]
@arpitmisraw this happened after merging your PR. Please try to fix ths

**Comment by Lasers67** [comment]
Give argument vel inside that is puck.reset(vel) I have made the changes in my pull request

**Comment by Aniq55** [comment]
Alright.

**Comment by CaptainDaVinci** [comment]
I think this issue is now resolved.
